name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # Repository isminde büyük harf varsa GHCR hata verir, bu yüzden hepsini küçük harfe zorluyoruz.
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute remote ssh commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Değişkenleri küçük harfe zorla (GHCR uyumu için)
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # GHCR'a login ol
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # En güncel imajı çek
          sudo docker pull ghcr.io/$REPO_LOWER:latest
          
          # Mevcut konteyneri (sd-api) durdur ve sil
          sudo docker stop sd-api || true
          sudo docker rm sd-api || true
          
          # Yeni konteyneri ayağa kaldır (Sizin manuel komutunuzla uyumlu)
          sudo docker run -d \
            -p 8081:8080 \
            --name sd-api \
            --restart always \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            -e MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
            -e MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e CORS_ALLOWED_ORIGINS="${{ secrets.CORS_ALLOWED_ORIGINS }}" \
            -e MAIL_HOST="${{ secrets.MAIL_HOST }}" \
            -e MAIL_PORT="${{ secrets.MAIL_PORT }}" \
            -e FIREBASE_CONFIG_JSON='${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' \
            ghcr.io/$REPO_LOWER:latest

          
          # Gereksiz imajları temizle
          sudo docker image prune -f


